### ISSUE TITLE
Automatic predicate methods for coerced booleans

### ISSUE THREAD

**Issue by jhirn** [palkan/anyway_config#114]
Given a config with a coerced boolean, it would be really nice to have predicate methods generated automatically. I'm thinking this is something that you might want to disable rather than opt-in to, but I'd be fine with either way. 

```ruby
class MyConfig < Anyway::Config
  attr_config enabled: "true"
  coerce_boolean enabled: :boolean
end

MyConfig.new.enabled? #=> true

# config
config.anyway_config.predicates_for_coerced_booleans = [false | true]

````

**Comment by jhirn** [comment]
If it's wanted.  I can try to put up a PR for this.

**Comment by palkan** [comment]
Hey!

We already create predicate methods when the default value is `true` or `false` (so, in you case `enabled: true` will ad the `#enabled?`) method: https://github.com/palkan/anyway_config/blob/83d79ccaf5619889c07c8ecdf8d66dcb22c9dc05/lib/anyway/config.rb#L105-L108

Anyway, I think, taking defined corrections into account also makes sense, so I'm open for a PR

**Comment by jhirn** [comment]
Thank you!
