### ISSUE TITLE
Support for no env prefix

### ISSUE THREAD

**Issue by bessey** [palkan/anyway_config#118]
## Is your feature request related to a problem? Please describe.

I am (considering) migrating a legacy codebase with >100 env vars and ~6 environments onto AnywayConfig. 

## Describe the solution you'd like

I would like to start our transition with one global AppConfig, and give teams the option to transition to namespaced configs and env vars as they see fit.

Therefore I would like to be able to pass in
```ruby
class AppConfig < Anyway::Config
  env_prefix false

  attr_config(:foo)
end
```
and that result in AppConfig's `foo` attribute being set by the env var `FOO`.

## Describe alternatives you've considered

I suppose I could write a custom "no namespace env" loader, but this would I believe affect all future Config objects since the loaders API is global only (I think?).

I could change my env vars, but this would be incredibly hazard prone to do all at once.

**Comment by palkan** [comment]
> I suppose I could write a custom "no namespace env" loader, but this would I believe affect all future Config objects since the loaders API is global only (I think?).

Correct. Right now loaders are global. I rejected the idea of per-class loaders customization, since it contradicts with the idea of a configuration class being a source-independent configuration store.

I think, `env_prefix ""` is a good API for this use-case.

**Comment by palkan** [comment]
Added in https://github.com/palkan/anyway_config/commit/5616a19b01aeb6d481fdbe6c3e3524f8253e917f
