### ISSUE TITLE
Deprecation warning for Rails secrets on Rails 7.1

### ISSUE THREAD

**Issue by composerinteralia** [palkan/anyway_config#136]
I ran isolator against an application using Rails 7.1 (currently unreleased) and noticed a deprecation warning coming from `lib/anyway/rails/loaders/secrets.rb` in this library:

```
DEPRECATION WARNING: `Rails.application.secrets` is deprecated in favor of `Rails.application.credentials` and will be removed in Rails 7.2.
```

**Comment by palkan** [comment]
Thanks for reporting! Should be fixed now. Will craft a new release soon.

**Comment by Laykou** [comment]
@palkan Can this be released, please? I see the last release is still from April 2023.

Thank you very much!

**Comment by palkan** [comment]
@Laykou It has been released a while ago (GitHub releases are not created for every gem release; check RubyGems).

**Comment by Laykou** [comment]
I'm sorry, I just checked Releases page here on Github https://github.com/palkan/anyway_config/releases where the most recent says 2.4.0 but I see RubyGems https://rubygems.org/gems/anyway_config/ is already at 2.6.2
