### ISSUE TITLE
Ruby 3.3 -  undefined local variable or method 'it' when installing from Github

### ISSUE THREAD

**Issue by Laykou** [palkan/anyway_config#146]
## What did you do?

I upgraded to latest version (becasue https://github.com/palkan/anyway_config/issues/136 is still not released) in master and executed some tests:

```ruby
gem 'anyway_config', github: 'palkan/anyway_config', branch: 'master'
```

## What actually happened?

Following error:

```
NameError:
  undefined local variable or method `it' for class Anyway::Config
# ./vendor/bundle/ruby/3.3.0/bundler/gems/anyway_config-f35efed69d95/lib/anyway/config.rb:157:in `block in on_load'
```

Is this somehow related to `it` method in Ruby 3.3?
https://allaboutcoding.ghinda.com/exploring-it-default-block-param-warning-in-ruby-33

## Environment

**Ruby Version:**

3.3

**Framework Version (Rails, whatever):**

Rails 7.1

**Anyway Config Version:**

2.6.2 (current master branch)

**Comment by palkan** [comment]
The latest released was published a week ago; you're good to use it.

The problem with installing from Github s worth exploring though.

Could you please share the output of the following commands:

```sh
cat Gemfile.lock | grep ruby-next

ls -al "$(bundle info anyway_config --path)/lib"

ls -al "$(bundle info anyway_config --path)/lib/.rbnext"
```

**Comment by Laykou** [comment]
I'm sorry, I just checked Releases page here on Github https://github.com/palkan/anyway_config/releases where the most recent says 2.4.0 but I see RubyGems https://rubygems.org/gems/anyway_config/ is already at 2.6.2

Here are the mentioned outputs:

```
❯ cat Gemfile.lock | grep ruby-next
      ruby-next-core (~> 1.0)
    ruby-next-core (1.0.0)
      ruby-next-core (>= 0.12.0)
```

```
❯ ls -al "$(bundle info anyway_config --path)/lib"
total 16
drwxr-xr-x   8 laykou  staff   256 Jan 17 18:00 .
drwxr-xr-x   7 laykou  staff   224 Jan 17 18:00 ..
drwxr-xr-x   8 laykou  staff   256 Jan 17 18:00 .rbnext
drwxr-xr-x  23 laykou  staff   736 Jan 17 18:00 anyway
-rw-r--r--   1 laykou  staff    55 Jan 17 18:00 anyway.rb
-rw-r--r--   1 laykou  staff  1224 Jan 17 18:00 anyway_config.rb
drwxr-xr-x   3 laykou  staff    96 Jan 17 18:00 generators
drwxr-xr-x   3 laykou  staff    96 Jan 17 18:00 rails
```

```
❯ ls -al "$(bundle info anyway_config --path)/lib/.rbnext"
total 0
drwxr-xr-x  8 laykou  staff  256 Jan 17 18:00 .
drwxr-xr-x  8 laykou  staff  256 Jan 17 18:00 ..
drwxr-xr-x  3 laykou  staff   96 Jan 17 18:00 2.6
drwxr-xr-x  3 laykou  staff   96 Jan 17 18:00 2.7
drwxr-xr-x  3 laykou  staff   96 Jan 17 18:00 3.0
drwxr-xr-x  3 laykou  staff   96 Jan 17 18:00 3.1
drwxr-xr-x  3 laykou  staff   96 Jan 17 18:00 3.2
drwxr-xr-x  3 laykou  staff   96 Jan 17 18:00 3.4
```

**Comment by palkan** [comment]
Thanks! All looks good.

Can you please share more stack lines from the error? I wonder what causes the load of the non-transpiled file 🤔

Also, what's the output of (one last guess):

```sh
ls -al "$(bundle info anyway_config --path)/lib/.rbnext/3.4"
```

**Comment by Laykou** [comment]
Strange, now it worked. Maybe my gems were just messed up locally. Since I switched branches, I tried again with:

```
gem 'anyway_config', github: 'palkan/anyway_config', branch: 'master'

bundle install

# run some spec
```

And I no longer see this err.r

Btw the command resulted in error that I do not have such file or directory.

```
ls -al "$(bundle info anyway_config --path)/lib/.rbnext/3.4"
ls: /Users/laykou/Projects/flowis/vendor/bundle/ruby/3.3.0/bundler/gems/anyway_config-f35efed69d95/lib/.rbnext/3.4: No such file or directory
```

I'm happy to close this issue unless there something else you'd like me to try

**Comment by palkan** [comment]
Thanks! Glad everything works now.

Yeah, let's close it then.
