### ISSUE TITLE
Is it possible to override file config though CLI options?

### ISSUE THREAD

**Issue by sponomarev** [palkan/anyway_config#25]
I know there is a way to use `COOLIO_CONF` env variable to override default `config/coolio.yml` location, but is there any solutions to use it with smth like `--conf myconfig/mycoolio.yml` ?

**Comment by palkan** [comment]
I should be implemented by the library. We do not perform options parsing in anyway config itself, it's up to the developer to decide when to do that. But technically, there is no way right now to initialize the config without loading from the default sources)
That means that options parsing is always happening after the file/env data fetching.

I see two options:
1) Reloading the config after parsing the options:

```ruby
class MyConfig < Anyway::Config
  extend_options do |parser, config|
    parser.on("-C PATH") do |path|
      env["MY_CONF"] = path
    end
  end
end

config = MyConfig.new
config.parse_options!(ARGV)
config.reload
# we might want to parse options again if
# we want them to have higher priority
config.parse_options!(ARGV)
```

2) Handle `--conf` option outside of Anyway Config.

For example, in AnyCable we have a CLI-only set of options, which could be used for that: https://github.com/anycable/anycable/blob/6ca8f3bbb099c582039da108f0b4b78216d3bd39/lib/anycable/cli.rb#L29

Again, we just set `ENV["ANYCABLE_CONF"]` if options is passed.

**Comment by palkan** [comment]
> doesn't work with rails-integrated anywayconfig

yeah, that was intentional; we assume that in Rails app you have a standard location for config files
