### ISSUE TITLE
Type cast precedence over describe_options

### ISSUE THREAD

**Issue by HenriqueMorato** [palkan/anyway_config#68]
## What did you do?

```ruby
SOME_CONFIG_CLIENT_ID="123456.123456"

class SomeConfig < ApplicationConfig
  attr_config :client_id

  describe_options(
    # In this case, you should specify a hash with `type`
    # and (optionally) `desc` keys
    client_id: {
       desc: "client identificator",
       type: String
     }
  )
  
  required :client_id
end
```

```bash
$ SomeConfig.new.client_id
$ => 123456.12

# =>SomeConfig.new.client_id.class
# => Float
```

## What did you expect to happen?

I was expecting the type to be string with full value

## Environment

**Ruby Version:** 2.7

**Framework Version (Rails, whatever):** Rails 6.1.0.alpha

**Anyway Config Version:** 2.0.6

Am i doing something wrong or is it a bug?

**Comment by palkan** [comment]
`describe_options` is only used with [`parse_options!`](https://github.com/palkan/anyway_config/blob/3a01215247c38e1f82e13dd9a820b1a8b044e6d1/lib/anyway/optparse_config.rb#L84), it has no effect for the default data loading mechanism.

There is no built-in support for type coercion. If you want to enforce a string value, you can use `on_load` hook:

```ruby
on_load { self.client_id = client_it.to_s if client_id }
```

I know, this is not ideal. There is a plan to add something `skip_auto_serialization` to config classes to disable any automatic type-casting; probably, will be a part of 2.1 release.
