### ISSUE TITLE
Tag Master Branch

### ISSUE THREAD

**Issue by edlewis89** [palkan/anyway_config#72]
The release 2.0.6 doesn't allow to set the known_environments like Rails.application.config.anyway_config.known_environments << "staging".  However the Master branch does.  Could you please tag Master so that we could use the new feature?
Thanks!

**Comment by ksouthworth** [comment]
I would also like to use the `Rails.application.config.anyway_config.known_environments << "staging"` feature but can't in the `2.0.6` gem release.

Thanks, I'm enjoying the gem so far, it's helping clean up a lot of our configuration woes!

**Comment by palkan** [comment]
Released in 2.1.0 as a _future_ feature: you must opt-in to use it via `config.anyway_config.future.use :unwrap_known_environments`. That's done to avoid breaking change by default. In the future (likely, v3.0), this would be the default behavior. /cc @progapandist
