### ISSUE TITLE
Config attribute not read from environment variables command line

### ISSUE THREAD

**Issue by lazing** [palkan/anyway_config#74]
## What did you do?
```
$ DIANPING_SITE=http://localhost rails c
Running via Spring preloader in process 21932
Loading development environment (Rails 6.0.3.4)
irb: warn: can't alias context from irb_context.
2.7.2 :001 > ENV["DIANPING_SITE"]
 => "http://localhost" 
2.7.2 :002 > DianpingConfig.site
 => nil 
2.7.2 :003 > DianpingConfig.env_prefix
 => "DIANPING" 
2.7.2 :009 > Anyway::VERSION
 => "2.1.0" 
```
## What did you expect to happen?
Get Value ENV_CONF=value
## What actually happened?
return nil
## Environment

**Ruby Version:**
ruby 2.7.2 MRI
**Framework Version (Rails, whatever):**
rails 6.0.3.4
**Anyway Config Version:**
2.1.0

**Comment by lazing** [comment]
for version 2.0.6 is OK. 

version 2.1.0 is announced for ruby 3.0, not work with 2.7.2

**Comment by palkan** [comment]
I see that you're using Spring; have you tried to run the console without it? (`DISABLE_SPRING=1 rails c` or `spring stop` first)

**Comment by palkan** [comment]
Hey @lazing! Any update?

**Comment by palkan** [comment]
Closed as stale
