### ISSUE TITLE
Can you release a new gem with the latest fixes?

### ISSUE THREAD

**Issue by slaught** [palkan/anyway_config#96]
## What did you do?

I tried to pull anyway_config gem from the repo and had the old release.

## What did you expect to happen?

I wanted the latest patches to fix the gem usage with Rails 7.

## What actually happened?

The old gem was installed.

## Environment

**Ruby Version:**. 2.7

**Framework Version (Rails, whatever):**  Rails 7

**Anyway Config Version:** latest released.

**Comment by palkan** [comment]
A new version will be out as soon as we merge #95. Stay tuned!

**Comment by palkan** [comment]
2.2.3 is out
