### ISSUE TITLE
Setting default_config_path in an initializer doesn't work.

### ISSUE THREAD

**Issue by anitagraham** [palkan/anyway_config#99]
## What did you do?
I created an initializer
```
# config/initializers/anyway_config.rb
Rails.application.config.anyway_config do |config|
  config.default_config_path =  Rails.root.join("config", "settings")
end
```

## What did you expect to happen?
I expected that my configuration files, in `config/settings` would be available to the application.

## What actually happened?
Configuration values were empty. 

## Additional context
When I put a settings file into `config/thing.yml` the configured settings were available.

When I put the configuration line into `config/application.rb` the configured settings from `config/settings` were available.
```
# config/application.rb
config.anyway_config.default_config_path =  Rails.root.join("config", "settings")
```
## Environment

**Ruby Version:** 2.7.5

**Framework Version (Rails, whatever):** 6.1.4.6

**Anyway Config Version:** 2.3.3

**Comment by fargelus** [comment]
@anitagraham hello!
Anyway Config doesn't support initializing with block. For initializer file recommended to pass desired values through usual assignment:

```ruby
# config/initializers/anyway_config.rb
Rails.application.config.anyway_config.default_config_path = Rails.root.join("config", "settings")
```

**Comment by anitagraham** [comment]
Thanks for your help, @fargelus , I think I have conquered it now.
